In [1]:
# Import the Python SDK
import google.generativeai as genai
# Used to securely store your API key
#from google.colab import userdata

GOOGLE_API_KEY="AIzaSyDKm5dvTpqlApCyg-WGvTk2WczjDEQLk-c"
genai.configure(api_key=GOOGLE_API_KEY)

In [2]:
model = genai.GenerativeModel('gemini-pro')

In [3]:
import pandas as pd

df_bird = pd.read_csv('df_bird.csv')
df_bird.head()

,question_id,db_id,question,evidence,SQL,difficulty,table_names_original,table_names,column_names_original,column_names,column_types,primary_keys,foreign_keys
0,0,california_schools,What is the highest eligible free rate for K-1...,Eligible free rate for K-12 = `Free Meal Count...,SELECT `Free Meal Count (K-12)` / `Enrollment ...,simple,"['frpm', 'satscores', 'schools']","['free and reduced-price meals', 'sat scores',...","[[-1, '*'], [0, 'CDSCode'], [0, 'Academic Year...","[[-1, '*'], [0, 'CDSCode'], [0, 'Academic Year...","['text', 'text', 'text', 'text', 'integer', 't...","[1, 30, 41]","[[1, 41], [30, 41]]"
1,1,california_schools,Please list the lowest three eligible free rat...,Eligible free rates for students aged 5-17 = `...,SELECT `Free Meal Count (Ages 5-17)` / `Enroll...,moderate,"['frpm', 'satscores', 'schools']","['free and reduced-price meals', 'sat scores',...","[[-1, '*'], [0, 'CDSCode'], [0, 'Academic Year...","[[-1, '*'], [0, 'CDSCode'], [0, 'Academic Year...","['text', 'text', 'text', 'text', 'integer', 't...","[1, 30, 41]","[[1, 41], [30, 41]]"
2,2,california_schools,Please list the zip code of all the charter sc...,Charter schools refers to `Charter School (Y/N...,SELECT T2.Zip FROM frpm AS T1 INNER JOIN schoo...,simple,"['frpm', 'satscores', 'schools']","['free and reduced-price meals', 'sat scores',...","[[-1, '*'], [0, 'CDSCode'], [0, 'Academic Year...","[[-1, '*'], [0, 'CDSCode'], [0, 'Academic Year...","['text', 'text', 'text', 'text', 'integer', 't...","[1, 30, 41]","[[1, 41], [30, 41]]"
3,3,california_schools,What is the unabbreviated mailing street addre...,NaN,SELECT T2.MailStreet FROM frpm AS T1 INNER JOI...,simple,"['frpm', 'satscores', 'schools']","['free and reduced-price meals', 'sat scores',...","[[-1, '*'], [0, 'CDSCode'], [0, 'Academic Year...","[[-1, '*'], [0, 'CDSCode'], [0, 'Academic Year...","['text', 'text', 'text', 'text', 'integer', 't...","[1, 30, 41]","[[1, 41], [30, 41]]"
4,4,california_schools,Please list the phone numbers of the direct ch...,Charter schools refers to `Charter School (Y/N...,SELECT T2.Phone FROM frpm AS T1 INNER JOIN sch...,moderate,"['frpm', 'satscores', 'schools']","['free and reduced-price meals', 'sat scores',...","[[-1, '*'], [0, 'CDSCode'], [0, 'Academic Year...","[[-1, '*'], [0, 'CDSCode'], [0, 'Academic Year...","['text', 'text', 'text', 'text', 'integer', 't...","[1, 30, 41]","[[1, 41], [30, 41]]"

In [10]:
index = 2

prompt = f"Table names: {df_bird.loc[index, 'table_names_original']}, Columns names: {df_bird.loc[index, 'column_names_original']}, generate a SQL query: {df_bird.loc[index, 'question']}"
response = model.generate_content(prompt)
df_bird.at[index, 'result'] = response.text

#print(prompt)
print(f'Gemini:\n{response.text}')

print(f'Gold:\n{df_bird.loc[index, "SQL"]}')

InternalServerError: 500 An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting

In [5]:
index = 99

prompt = f"Columns names: {df_bird.loc[index, 'column_names_original']}, generate a SQL query: {df_bird.loc[index, 'question']}"
response = model.generate_content(prompt)
df_bird.at[index, 'result'] = response.text

print(prompt)
print(response.text)

Columns names: [[-1, '*'], [0, 'account_id'], [0, 'district_id'], [0, 'frequency'], [0, 'date'], [1, 'card_id'], [1, 'disp_id'], [1, 'type'], [1, 'issued'], [2, 'client_id'], [2, 'gender'], [2, 'birth_date'], [2, 'district_id'], [3, 'disp_id'], [3, 'client_id'], [3, 'account_id'], [3, 'type'], [4, 'district_id'], [4, 'A2'], [4, 'A3'], [4, 'A4'], [4, 'A5'], [4, 'A6'], [4, 'A7'], [4, 'A8'], [4, 'A9'], [4, 'A10'], [4, 'A11'], [4, 'A12'], [4, 'A13'], [4, 'A14'], [4, 'A15'], [4, 'A16'], [5, 'loan_id'], [5, 'account_id'], [5, 'date'], [5, 'amount'], [5, 'duration'], [5, 'payments'], [5, 'status'], [6, 'order_id'], [6, 'account_id'], [6, 'bank_to'], [6, 'account_to'], [6, 'amount'], [6, 'k_symbol'], [7, 'trans_id'], [7, 'account_id'], [7, 'date'], [7, 'type'], [7, 'operation'], [7, 'amount'], [7, 'balance'], [7, 'k_symbol'], [7, 'bank'], [7, 'account']], generate a SQL query: Among the accounts who have loan validity more than 12 months, list out the accounts that have the highest approved amount and have account opening date in 1993.
```sql
WITH RankedLoans AS (
  SELECT
    account_id,
    loan_id,
    amount,
    ROW_NUMBER() OVER (PARTITION BY account_id ORDER BY amount DESC) AS rank
  FROM loans
  WHERE
    duration > 12
)
SELECT
  account_id
FROM RankedLoans
JOIN accounts
  ON RankedLoans.account_id = accounts.account_id
WHERE
  rank = 1 AND STRFTIME('%Y', date) = '1993';
```